
CUDA_INCLUDE += -I$(CUDNNROOT)/include
CUDA_FLAGS += -DHAVE_CUDNN=1 -DHAVE_CUDA=1
CXXFLAGS += -DHAVE_CUDNN=1 -DHAVE_CUDA=1 -I$(CUDNNROOT)/include
CUDA_LDFLAGS += -L$(CUDNNROOT)/lib64 -Wl,-rpath,$(CUDNNROOT)/lib64
CUDA_LDLIBS += -lcudnn
